### ISSUE TITLE
Exclude clientId and secret in BaseClientRequest

### ISSUE THREAD

**Issue by mazitbehalf** [plaid/plaid-java#106]
We would like to audit requests and responses we get from you.
Is there a way to exclude clientId and secret in BaseClientRequest?
In current implementation it is being saved with the request data.
Is there a way to make it transient so it wont be persistent in our data base? 
Thanks!

**Comment by michaelckelly** [comment]
@mazitbehalf - What are you trying to audit about the outbound requests? You should already be able to audit responses without issue. Could you log to your auditing system some combination of the Plaid item ID (or account ID) that you are making the API request for and what Plaid's response was? Perhaps only record if there was a non-200 status code, indicating that some type of error occurred. All Plaid response bodies include a request ID that is helpful for debugging too.

**Comment by mazitbehalf** [comment]
Ok, I'll try to overcome it in a different way.. Thanks!
