### ISSUE TITLE
Android TransactionsGetResponse not working

### ISSUE THREAD

**Issue by TheoSeo93** [plaid/plaid-java#123]
I tried following the code on this https://plaid.com/docs/api/#transactions

but I keep getting this message when getting `Response<TransactionsGetResponse>`
 ```
TransactionsGetRequest request =
                new TransactionsGetRequest(token, startDate, endDate)
                        .withCount(100);
     txnResponse = plaidClient.service()
                            .transactionsGet(request).execute();
```
`accesstoken` was successfully acquired, but after passing the token to the request and getting the response, I get this message

`Response{protocol=http/1.1, code=400, message=Bad Request, url=https://sandbox.plaid.com/transactions/get}`

```
{
  "display_message": null,
  "error_code": "NOT_FOUND",
  "error_message": "invalid route: /transactions/get",
  "error_type": "INVALID_REQUEST",
  "request_id": "Q1NY6"
}
```

I don't see what kind of this error "invalid route" means. 
Am I missing something?

**Comment by michaelckelly** [comment]
@TheoSeo93 - It sounds like you may be making authenticated Plaid API calls from a client-side device -- that would mean that your API keys (client ID and secret) are also stored client-side. You need to make all API calls that retrieve data from your backend server.

It looks like the `/transactions/get` request being made is actually `GET /transactions/get` rather than the expected `POST /transactions/get`.

**Comment by TheoSeo93** [comment]
So that means I have to set up a server first, but how come the request is being made as GET, not POST? I see there is no function to set the http method as GET or POST from `TransactionsGetRequest` how can I set the http method?

**Comment by michaelckelly** [comment]
@TheoSeo93 - that's a good question, the endpoint is specifically defined as `POST`, https://github.com/plaid/plaid-java/blob/master/src/main/java/com/plaid/client/PlaidApiService.java#L177-L178. Can you confirm that you're using the most up-to-date version of plaid-java? 

But yes to answer your question, you'll need to have your app talk to your server's API and your server's API is what should be communicating with Plaid.

**Comment by TheoSeo93** [comment]
Yes, I am using the most recent one, plaid-java:3.0.4. So does that mean I cannot use the code from the API document from https://plaid.com/docs/api/#transactions?

**Comment by davidzhanghp** [comment]
@TheoSeo93 in general you do not want to store secrets on your client app. the general best practice is usually to make the calls server side (where the secret is safe) and pass the relevant information to the client.

With regards to the SDK error, can you please try with the latest version of plaid-java?
