### ISSUE TITLE
Allow the ability to override the connect and read timeouts

### ISSUE THREAD

**Issue by heidiwags** [plaid/plaid-java#143]
Currently there is no way to override the read and connect timeout.

I think the builder should be changed to allow passing in a custom configuration, rather than having it default to 300s and 5s.

**Comment by davidzhanghp** [comment]
Hi @heidiwags. This was fixed as part of https://github.com/plaid/plaid-java/pull/144. Before building the PlaidClient you can get access to the underlying OkHttpClientBuilder and set the timeouts as you wish.

**Comment by heidiwags** [comment]
Thanks! Just so that I'm implementing correctly - this is what i have for the sandbox:
`        PlaidClient.Builder sandboxBuilder = PlaidClient.newBuilder().clientIdAndSecret(clientId, sandboxSecret)
                .publicKey(publicKey)
                .sandboxBaseUrl()
                .logLevel(HttpLoggingInterceptor.Level.BODY);
        sandboxBuilder.okHttpClientBuilder()
                .readTimeout(150, TimeUnit.SECONDS)
                .connectTimeout(3, TimeUnit.SECONDS)
                ;
        PlaidClient sandboxPlaidClient = sandboxBuilder.build();`

Also - 300s = 5 minutes for the default - are there suggestions for more reasonable read timeouts than 5 minutes? 2.5m still feels long as well - but I'm not sure what the average plaid request takes (we use the API to generate the dwolla token, balance check, generate the access token, and generate the public token

**Comment by davidzhanghp** [comment]
@heidiwags , the read and connect timeouts are a bit misleading-ly named.
These are socket level timeouts.

The read timeout is the maximum amount of time between successive reads. The connect timeout is similarly a socket-level timeout.

I would set these on the order of seconds, as it limits how long okhttp will wait on socket connect and how long successive reads on the same socket can take to succeed. It does not set a maximum duration for a request.
