### ISSUE TITLE
Cannot instantiate PlaidClient

### ISSUE THREAD

**Issue by debasishgt** [plaid/plaid-java#151]
I am trying to create an instance of the PlaidClient but it's not working:

Here is the snippet:

```
plaidClient = PlaidClient.newBuilder()
                    .clientIdAndSecret(clientId, clientSecret)
                    .publicKey(publicKey)
                    .developmentBaseUrl() 
                    .build()
```

The weird part is it't not even throwing an exception.

I had to put logs in a finally block to see the plaidClient is null

I am using Java 1.7 & plaid-java 4.0.3

Am I missing something?

**Comment by davidzhanghp** [comment]
@debasishgt this is quite old (boththe ticket and the java version). Please try with the latest version of Java.
