### ISSUE TITLE
Transaction amount 

### ISSUE THREAD

**Issue by sholavanalli** [plaid/plaid-java#156]
Transaction amount is positive for expenses and negative for earnings/income. Shouldn't this be opposite? I verified this with checking account and credit card accounts and behavior is the same.

**Comment by davidzhanghp** [comment]
Hi @sholavanalli, this may seem a bit unintuitive, but there is additional documentation here:

https://support.plaid.com/hc/en-us/articles/360008413653-Negative-transaction-amount

**Comment by PeculiarE** [comment]
Hi @davidzhanghp.....the link provided takes me to the general API docs page. Seems the article has been moved. Could you please provide an updated link? Thanks.

**Comment by phoenixy1** [comment]
https://plaid.com/docs/api/products/transactions/#transactions-sync-response-added-amount
