### ISSUE TITLE
Fixed precision data types for money representation.

### ISSUE THREAD

**Issue by willjschmitt** [plaid/plaid-java#172]
Since the response data indicates a limited precision, which is appropriate for money, where we only have cent precision (at least for USD), is it a conscious decision that the types for decimal values are `Double` instead of something with fixed precision like `BigDecimal`?

Since we expect to handle this data as fixed precision data, it would be nice not to have to handle the risk of lost precision in adapting `Double`s back to `BigDecimals` with the loss of precision.

**Comment by davidzhanghp** [comment]
@willjschmitt plaid's API is json based and we return cents/other monetary amounts as json numbers. The limited precision is okay for returning cents, and we would not gain any safety by converting it to BigDecimals in the java SDK (since the API returns json doubles).
