### ISSUE TITLE
logo images not returning with institution.getLogo() - returns name instead

### ISSUE THREAD

**Issue by rickgonzalez** [plaid/plaid-java#182]
String myinstitutionid = context.getQueryParameters().getFirst("institutionid") ; 
        
         
         // Use builder to create a client   
        PlaidClient client = PlaidClient.newBuilder()
        .clientIdAndSecret(env.getProperty("plaid.client"), env.getProperty("plaid.secret"))
        .publicKey(env.getProperty("plaid.pubkey")) // optional. only needed to call endpoints that require a public key
        .baseUrl(env.getProperty("plaid.baseurl"))
         .build();
        
         Response<InstitutionsGetByIdResponse> response;
         response = client.service().institutionsGetById(new InstitutionsGetByIdRequest(myinstitutionid).withIncludeOptionalMetadata(true))
                 .execute();
       
        if (response.isSuccessful()){
        Institution institution = response.body().getInstitution();
        
        String myname = institution.getName();
        String mylogo = institution.getLogo();
        
**--> In the sandbox, mylogo ends up as "BB&T - Online Banking" or another name of a bank based on institution id**

pom.xml entry - 5.1.4
  <dependency>
            <groupId>com.plaid</groupId>
            <artifactId>plaid-java</artifactId>
            <version>5.1.4</version>
        </dependency>

**Comment by davidzhanghp** [comment]
@rickgonzalez unfortunately I am unable to repro this. Can you please upgrade to the latest plaid-java version and see if you can replicate?

Please re-open a ticket if this resurfaces.
