### ISSUE TITLE
Transaction object not in sync with response/API documentation

### ISSUE THREAD

**Issue by signari** [plaid/plaid-java#191]
The Transaction object included in the TransactionsGetResponse class version 5.1.5 does not align with the actual JSON response or API documentation version 2019-05-29.

Git: [https://github.com/plaid/plaid-java/blob/master/src/main/java/com/plaid/client/response/TransactionsGetResponse.java](url)

API: [https://plaid.com/docs/#transactions](url)

The Transaction class is defined as: 

```  
public static final class Transaction {
    private String accountId;
    private Double amount;
    private String isoCurrencyCode;
    private String unofficialCurrencyCode;
    private List<String> category;
    private String categoryId;
    private String date;
    private Location location;
    private String name;
    private String originalDescription;
    private PaymentMeta paymentMeta;
    private Boolean pending;
    private String pendingTransactionId;
    private String transactionId;
    private String transactionType;
    private String accountOwner;
```

The JSON response includes a "payment_channel" field, also detailed in the API documentation and is said to replace the deprecated "transaction_type" field, but it is not included in the Java Transaction object above.

**Comment by stephenjayakar** [comment]
Hey @signari!  Good callout, this response model is definitely not in sync.  We're planning on generating our API in next one or two major releases, so it'll be hard-pinned to API version 2020-09-14.  This specific parameter has been added in the above PR in this thread.
