### ISSUE TITLE
Do we have a chance to customize settings for Retrofit like addCallAdapterFactory?

### ISSUE THREAD

**Issue by johnchlorophyll** [plaid/plaid-java#234]
Hi Team, I'm trying to add something to the Retrofit like Resilience4j.
https://resilience4j.readme.io/docs/retrofit

The problem is after the client was built, we don't have a chance to add anything like that in retrofit.addCallAdapterFactory. And we don't have any ways to set that before the client was built.

Can we have a solution for that?
Thanks.

**Comment by cgfarmer4** [comment]
hi @johnchlorophyll- We don't provide support for external libraries. If you'd like to file a PR, we'd be happy to take it into consideration for your use case.
