### ISSUE TITLE
Consider using BigDecimal rather than Double to represent monetary amounts

### ISSUE THREAD

**Issue by totof3110** [plaid/plaid-java#235]
Java's doubles and floats are notoriously bad at representing monetary amounts. E.g.:
- https://dzone.com/articles/never-use-float-and-double-for-monetary-calculatio
- https://stackoverflow.com/questions/3413448/double-vs-bigdecimal
- https://medium.com/@vaibhav0109/choosing-data-type-for-monetary-calculation-in-java-float-double-or-bigdecimal-ac6f52e57740

Would you consider switching Double to BigDecimal in one of the major releases?

**Comment by cgfarmer4** [comment]
hi @totof3110 - Thanks for sharing. I have noted your feature request for the next version. I will update here if/when this lands. Closing for now.
