### ISSUE TITLE
Link Token Update

### ISSUE THREAD

**Issue by hkothari** [plaid/plaid-java#237]
Is there a way to do this with the Java API: https://plaid.com/docs/#create-link-token-for-update 

It seems like the LinkTokenCreateRequest is pretty strict. Can I just fill in nulls to get the desired outcome?

**Comment by mykhailovoitovych** [comment]
any update on this issue?

**Comment by hkothari** [comment]
From my usage, it appears the answer is yes, you can just fill in nulls for the values you don't need.

**Comment by otherchen** [comment]
Hey! Yes, you should be able to just pass in nulls or empty lists for the values you don't need.

If you go to https://plaid.com/docs/#create-link-token-for-update and filter the code examples for `Java`, you should be able to see what works.

![Screen Shot 2020-11-04 at 1 39 29 PM](https://user-images.githubusercontent.com/8565076/98170688-45886000-1ea3-11eb-9f32-d8742b0c9730.png)

Closing this issue for now! Please let me know if you still have questions regarding this :)
