### ISSUE TITLE
Not an issue but...

### ISSUE THREAD

**Issue by CameronBurley** [plaid/plaid-java#261]
Hello! My name is Cameron Burley and I am a computer science student trying to create a program. I'd like for my program to text my bank account information to me every morning. My question is, how exactly do I use the API, I'm fairly new and I'm unsure what to do. How do I import the external jar files in order to import the library? I think my project setup is messed up. Thank you for your time!

**Comment by jessekunze** [comment]
The easiest way to get into it is to do the [QuickStart ](https://plaid.com/docs/quickstart/)  project. 

Once you figure out how that works, and fiddle around with it for a few days you can start to slowly add changes to match what you want to happen.

**Comment by skylarmb** [comment]
Hi Cameron! Agreed, check out the plaid quickstart! The quickstart app has examples of using plaid-java: https://github.com/plaid/quickstart/tree/master/java
