### ISSUE TITLE
Error type should not be called `Error`

### ISSUE THREAD

**Issue by stevenschlansker** [plaid/plaid-java#282]
The new 9 beta Plaid client uses a type called `Error` to model error responses.  While attempting to use it as suggested by the readme, I of course discovered that due to the implicit `java.lang.Error` import, it is always required to fully qualify Plaid's error type.

There's no reason to shadow such a ubiquitous type like `java.lang.Error` and confusing the two is Very Bad.

Please consider renaming this new `Error` class before releasing the final version.

**Comment by phoenixy1** [comment]
@stephenjayakar fyi, another good pre-ga checklist item

**Comment by phoenixy1** [comment]
this has been fixed, we now have a `PlaidError` type
