### ISSUE TITLE
How to set "client_name" on Plaid version 2020-09-14

### ISSUE THREAD

**Issue by FranOlivaDevEngineer** [plaid/plaid-java#300]
Hello!
The interaction with Plaid is working properly. Now I want to add the client name to my connection code snippet . I am using this way to connect:

```
 HashMap<String, String> apiKeys = new HashMap<String, String>();
        apiKeys.put("clientId", clientId);
        apiKeys.put("secret", secret);
        apiKeys.put("plaidVersion", "2020-09-14");
        ApiClient apiClient;
        apiClient = new ApiClient(apiKeys);
        apiClient.setPlaidAdapter(ApiClient.Sandbox);// or equivalent, depending on which environment you're calling into
        plaidClient = apiClient.createService(PlaidApi.class);
```
        
 POM.xml dependency:
```
 <dependency>
     <groupId>com.plaid</groupId>
     <artifactId>plaid-java</artifactId>
     <version>9.0.0-beta-1</version>
</dependency>
```
        
I didn't find the way to set client_name in this version. Somebody can help me with this? Thanks!

**Comment by FranOlivaDevEngineer** [comment]
The documentation regading client_name attribute https://plaid.com/docs/api/tokens/#link-token-create-request-client-name

**Comment by phoenixy1** [comment]
@FranOlivaDevEngineer you're using the beta libraries, right? If you go to the page you linked and select the beta sample code, client_name is set on line 17 of the sample. Here's the LinkTokenCreateRequest config from the sample:

```
LinkTokenCreateRequest request = new LinkTokenCreateRequest()
  .user(user)
  .clientName("Plaid Test App")
  .products(Arrays.asList(Products.AUTH))
  .countryCodes(Arrays.asList(CountryCode.US))
  .language("en")
  .webhook("https://example.com/webhook")
  .linkCustomizationName("default")
  .accountFilters(accountFilters);
```
