### ISSUE TITLE
Upgrade okhttp to 4.x

### ISSUE THREAD

**Issue by alejandrod-f** [plaid/plaid-java#356]
Hi, the library uses a previous version of okhttp and is causing issues with other libraries as 3.x is not compatible

**Comment by phoenixy1** [comment]
@vorpus based on the generator docs (which might be out of date) it looks like this is OpenAPI generator behavior and I don't know if it's something we can override? Looking at the release notes for OpenAPI generator, I don't see any indication that they've upgraded to 4.x for okhttp. https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/java.md

**Comment by alejandrod-f** [comment]
Side comment... they might have not and now sure why the OpenAPI generator matters. 
But, we are having issues with other libraries that use okhttp 4.10 and plaid-java.

**Comment by phoenixy1** [comment]
(@alejandrod-f OpenAPI generator is the tool that we use to create the client libraries)

**Comment by phoenixy1** [comment]
@alejandrod-f this is now done in the latest version of the java clib!
