### ISSUE TITLE
null logos for institutions

### ISSUE THREAD

**Issue by haotian-coterie** [plaid/plaid-java#368]
Not sure if anyone else has run into this, but using `getInstitutionById` with `include_optional_metadata` often comes back without a logo for the institution (for very large and common ones like Chase/Wells Fargo). 

What I've found is an undocumented option `include_display_data` does return this, but is not supported by the library. 
<img width="874" alt="Screen Shot 2022-11-25 at 2 54 13 PM" src="https://user-images.githubusercontent.com/106164952/204050058-201e9863-e620-4101-93b1-f7dc4a78240d.png">
<img width="641" alt="Screen Shot 2022-11-25 at 2 53 52 PM" src="https://user-images.githubusercontent.com/106164952/204050061-bd1f6476-8e9c-40ff-b4d8-b7befb446693.png">

**Comment by phoenixy1** [comment]
my understanding is that this behavior is by design -- not all institutions support this. include_display_data is not intended for external use and we do not plan to add it to the library.
