### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by seljabali** [plaid/plaid-java#383]
Hi team 👋 

Thank you for all that you do. It's most appreciated.

I was wondering if it would be possible to write up Github Releases alongside new tags? It would go a long way for developers like myself to know what has changed from v15.1.0 to v16.0.0 for example more recently.

Thanks again!
-Sami

**Comment by phoenixy1** [comment]
Have you seen changelog.md? https://github.com/plaid/plaid-java/blob/master/CHANGELOG.md

I think what you're looking for should be in there.
