### ISSUE TITLE
confused by changelog timestamps

### ISSUE THREAD

**Issue by alexanderbaumann-toast** [plaid/plaid-java#387]
https://github.com/plaid/plaid-java/blame/56ae2c06ba22cdf36b9de29f4b2b6ace212c801d/CHANGELOG.md#L344

this says the update was 

### 2020-09-14_1.336.1
- Add `signal` to Products array.

But Plaid's website shows  Feb 2023 
https://plaid.com/docs/changelog/#february-2023

**Comment by phoenixy1** [comment]
Oh I see the cause of the confusion! I agree we do this a little weirdly, but the "date" in the changelog is not the time stamp of the change, it is the API version name (2020-09-14) with a version number (used to version the OpenAPI file) appended to it. Hopefully that clears things up!
