### ISSUE TITLE
updateAuth uses wrong endpoint

### ISSUE THREAD

**Issue by okalex** [plaid/plaid-java#39]
The endpoint hit by `updateAuth` is a POST to `/auth/get` but according to [the API docs](https://plaid.com/docs/#retrieve-data), this is actually the endpoint for "retrieve data". This should instead be called `getAuth` and an `updateAuth` method should instead submit a PATCH request to `/auth` as specified in the docs.

**Comment by erimag** [comment]
That depends on what you mean by "updateAuth". But I see your point. I'll review that in conjunction with other changes. Thanks!
