### ISSUE TITLE
Example code in README.md has many mistakes

### ISSUE THREAD

**Issue by siudeks** [plaid/plaid-java#404]
Copy and paste example java code from README to e.g. intellij and you see compilation errors related to inproper use of some elements, e.g. plaidClient()

**Comment by phoenixy1** [comment]
thanks for the report! The code in the README isn't intended to be run exactly as is without more context, but I've submitted some PRs to address the most egregious stuff (https://github.com/plaid/plaid-java/pull/407 and https://github.com/plaid/plaid-java/pull/408). If there are other specific things you see that should be fixed, please comment.
