### ISSUE TITLE
PhysicalDocumentExtractedData is missing a name field

### ISSUE THREAD

**Issue by rrudden** [plaid/plaid-java#425]
The API docs for Identity Verification state that the extracted data JSON object should look like this:

"extracted_data": {
          "id_number": "AB123456",
          "category": "drivers_license",
          "expiration_date": "1990-05-29",
          "issuing_country": "US",
          "issuing_region": "IN",
          "date_of_birth": "1990-05-29",
          "address": {
            "street": "123 Main St. Unit 42",
            "city": "Pawnee",
            "region": "IN",
            "postal_code": "46001",
            "country": "US"
          },
          "name": {
            "given_name": "Leslie",
            "family_name": "Knope"
          }
        }

This json appears to correspond with the PhysicalDocumentExtractedData class, but there is no name field in this class.

**Comment by phoenixy1** [comment]
This has been resolved in version 26.0.0 of the Plaid Java client library: https://github.com/plaid/plaid-java/blob/3409688f32ea3e5969662d51372a7db3dac87e03/src/main/java/com/plaid/client/model/PhysicalDocumentExtractedData.java#L65
