### ISSUE TITLE
InstitutionsGetById/includeOptionalMetadata doesn't work

### ISSUE THREAD

**Issue by Sam-Kruglov** [plaid/plaid-java#432]
Setting this to true but not getting back logo. Using a sandbox user. When Link UI opens, I see the citi bank logo, click on it, enter user, see accounts, but in data there's no citi logo

**Comment by phoenixy1** [comment]
So [per the docs](https://plaid.com/docs/api/institutions/#institutions-get-response-institutions-logo), "not all institutions' logos are available" via `/institutions/get_by_id`. Citi is one of the institutions whose logos is not available, so this is expected behavior.

**Comment by Sam-Kruglov** [comment]
oh, got it, I assumed if the logo was showing in the link UI then it would be available. That's strange but thanks
