### ISSUE TITLE
usePlaidLink.open(token=null) fails silently

### ISSUE THREAD

**Issue by Sam-Kruglov** [plaid/plaid-java#435]
```ts
const [linkResult, setLinkResult] = useState<{
    loading: boolean
    errorMessage?: string | null
    errorType?: string | null
  }>({ loading: true })
const { open, ready, error } = usePlaidLink({token: undefined, ...})
if (ready) open()
if (error) return <Err500/> // always null
if (linkResult.loading) return <Spinner/> // showing this forever
```

**Comment by phoenixy1** [comment]
This doesn't appear to be related to the plaid-java client library -- if you're having an issue with `usePlaidLink.open` feel free to file this against https://github.com/plaid/react-native-plaid-link-sdk with this form filled out -- https://github.com/plaid/react-native-plaid-link-sdk/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=
