### ISSUE TITLE
Release 0.3.0 isn't in maven central

### ISSUE THREAD

**Issue by bobspiller** [plaid/plaid-java#58]
Ref: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.plaid%22%20AND%20a%3A%22plaid-java%22

The README says 0.3.0 should be the current version.   And there have been quite a few improvements since 0.2.12.

Would someone on the project please do the deploy?

Thanks.

**Comment by a86c6f7964** [comment]
looks like 0.3.1 is now

**Comment by bobspiller** [comment]
Yep, looks good.  No longer an issue.   This can be closed.
