### ISSUE TITLE
Readme references 2.0.0 but I don't see any version past 0.3.2 in the Maven link

### ISSUE THREAD

**Issue by dadambickford** [plaid/plaid-java#70]
Is this just pending a release or not done yet? Sorry not really an issue but I couldn't think of a better way to reach out about the status.

I see the `<version>2.0</version>` but the [link above that part](https://search.maven.org/#search%7Cga%7C1%7Cplaid-java) only shows up to v0.3.2

**Comment by mihahribar** [comment]
+1

**Comment by OscarGodson** [comment]
ETA?

**Comment by dwoodworth91** [comment]
+1

**Comment by dadambickford** [comment]
@mihahribar @OscarGodson @dwoodworth91
FWIW currently I have manually included the version in master to my scala project until there is resolution on this. I had to add the retrofit2 and okhttp3 dependencies to my own project and then it worked. Janky for sure, but it's working and reaching plaid 👍

**Comment by DigitalwebNigeria** [comment]
+1.
I looked through, and I thought the readme and the version on maven central are not in sync.

**Comment by mihahribar** [comment]
@dadambickford did that too, worked fine, but would prefer the maven way 👍

**Comment by michaelckelly** [comment]
Thanks for the ping here @all and apologies for the lack of reply. We're sorting out permissions issue to get the release out. The 2.0.0 release is merged in this repository and ready-to-go (the integration tests provide a good jumping off point).

We're working on an alternative name to publish the jar to resolve this ASAP.

**Comment by dadambickford** [comment]
Thanks for the update @michaelckelly.

@mihahribar the scala project I'm working in doesn't use the maven(?) dependencies file like that, but indeed I did need to add all 4 to my file. 2 from each retrofit2 and okhttp3.

```
libraryDependencies += "com.squareup.retrofit2" % "retrofit" % "2.1.0"
libraryDependencies += "com.squareup.retrofit2" % "converter-gson" % "2.1.0"
libraryDependencies += "com.squareup.okhttp3" % "okhttp" % "3.6.0"
libraryDependencies += "com.squareup.okhttp3" % "logging-interceptor" % "3.6.0"
```

**Comment by dwoodworth91** [comment]
If it helps anybody, I was able to get going by checking the project out with git, then building it with Maven and dropping it into a configured local Maven repo - mimicking the directory and naming scheme that you can ape by looking at Maven Central.

1. Rename JAR to "plaid-java-2.0.jar" It'll be under [project-root] -> target, and named "plaid-java-apiv2-2.0.jar"
2. rename project POM to "plaid-java-2.0.pom"
3. Drop both files into: [repo-root] -> com -> plaid -> plaid-java -> 2.0

It is already set up to build a JAR, so if you know Maven, you should be golden. If you don't want to configure a local Maven repo in your main project, you could probably also just do what is described above in your local Maven cache.

**Comment by ufdeveloper** [comment]
Thanks for the detailed procedure to get it working @dwoodworth91

**Comment by dwoodworth91** [comment]
@ufdeveloper , glad you found it useful!

**Comment by alejandrod** [comment]
+1

**Comment by michaelckelly** [comment]
@dwoodworth91 - Thank you for supplying the workaround in the interim.

I hope that we can resolve the permissions issues once and for all this week -- the POM file should be updated to reflect the appropriate repository and package names (apologies for not having those properly up-to-date).

A few unit tests that were failing have also been fixed (mainly due to introducing support for the Income product).

The 2.0.0 / 2.1.0 Jar is successfully building with tests passing locally but a permissions issue is preventing the release to be pushed to the Sonatype repository. Once that's resolve, we should be unblocked for the release.

Thank you to everyone for the patience and help here and please follow up here with any additional questions.

**Comment by Jmittleman17** [comment]
@michaelckelly any update on when the jar will be available on Maven?

**Comment by HeathNaylor** [comment]
Still nothing on Maven.

**Comment by DigitalwebNigeria** [comment]
@michaelckelly any update with the jar being pushed to maven?

**Comment by michaelckelly** [comment]
`2.1.0` has been published to maven!

https://oss.sonatype.org/service/local/repositories/releases/content/com/plaid/plaid-java/2.1/plaid-java-2.1.jar

It should sync to the central Maven repository shortly

**Comment by michaelckelly** [comment]
Looks like the release has synced to Maven Central - https://search.maven.org/#artifactdetails%7Ccom.plaid%7Cplaid-java%7C2.1%7Cjar.

If someone is able to test, I'd love to know if we got this working!

**Comment by mihahribar** [comment]
Worked for me 👍

**Comment by michaelckelly** [comment]
Great thank you for confirming @mihahribar - going to go ahead and close this issue for now.
