### ISSUE TITLE
Support currencyCode

### ISSUE THREAD

**Issue by alejandrod** [plaid/plaid-java#75]
As explained here:
https://support.plaid.com/customer/en/portal/articles/2600022-transaction-currencies
There is a currencyCode field which is not represented in the current responses.

This has to be at the institution and the transaction level (as the transaction might be different)

**Comment by mihahribar** [comment]
Any news regarding this?

**Comment by mihahribar** [comment]
Would really appreciate if somebody would get around to adding this 👍

**Comment by alejandrod** [comment]
any news?

**Comment by alejandrod** [comment]
cool!
