### ISSUE TITLE
TransactionsGetResponse inner classes are not static inner classes

### ISSUE THREAD

**Issue by dustinconrad** [plaid/plaid-java#81]
Is there a reason that TransactionsGetResponse.Transaction/PaymentMeta/Location are not static inner classes?

The inner classes of some other responses (for example, IdentityGetResponse) are static.

**Comment by jeeyoungk** [comment]
These classes shouldn't be nonstatic inner classes. I have a PR out to fix it: https://github.com/plaid/plaid-java/issues/81
