### ISSUE TITLE
Please support Apex porcessor token creation

### ISSUE THREAD

**Issue by AndyMoreland** [plaid/plaid-java#86]
Hello!

Right now this endpoint: https://plaid.com/docs/link/apex-cb62307bf04c117278a4/ (for creating apex processor tokens) does not appear to be modelled in the java lib, while the stripe endpoint is. Is it easy to add this?

Best,

Andy

**Comment by michaelckelly** [comment]
@AndyMoreland - #87 will add support for this!

**Comment by michaelckelly** [comment]
Support has been added in the `2.1.3` release
