### ISSUE TITLE
Mark optional response fields as so

### ISSUE THREAD

**Issue by davidselassie** [plaid/plaid-java#88]
There are many fields in the API response JSON that can be `null`, but these are in no way annotated in the client library. Since the using code has to specifically handle nulls in every one of the fields that are being used, it would be nice if all of those used `Optional` or were annotated by `@Nullable` to mark that that is necessary to do that handling.

Relatedly, when a field that's a JSON array is missing, the API also returns it as null, which means that the consuming code has to handle null instead of the empty list. It would be nice if the JSON deserializer converted nulls to empty lists for list fields, since there's no semantic difference, both mean nothing is there.

**Comment by skylarmb** [comment]
closing as stale / obsolete, feel free to re-open if that is incorrect.
