### ISSUE TITLE
Get Apex Processor Token returns `null` always

### ISSUE THREAD

**Issue by AndyMoreland** [plaid/plaid-java#90]
Hi!

I'm using `plaid-java` version `2.1.3`. I'm trying to get an apex processor token. I think there's a bug in the response class. When I enable HTTP logging for my client I see a response come back that looks like:

```
{
  "processor_token": "...",
  "request_id": "..."
}
```

but when I use the deserialized response and do `.getApexProcessorToken()` I get `null`. 

I am not familiar with the HTTP client framework being used in this project, but should `getApexProcessorToken()` be named `getProcessorToken()`?

**Comment by AndyMoreland** [comment]
I changed `getApexProcessorToken` and the corresponding private instance variable to `getProcessorToken` and things are working now.

**Comment by AndyMoreland** [comment]
Thanks!

**Comment by michaelckelly** [comment]
@AndyMoreland - this was just released to Maven central as `2.1.4`, Maven typically takes a few hours to catch up and sync though
