### ISSUE TITLE
I am getting NoClassDefFoundError exception

### ISSUE THREAD

**Issue by Villonava** [plaid/plaid-java#93]
// Use builder to create a client 
PlaidClient plaidClient = PlaidClient.newBuilder()
  .clientIdAndSecret("your_client_id", "your_secret")
  .publicKey("your_public_key") // optional. only needed to call endpoints that require a public key
  .sandboxBaseUrl() // or equivalent, depending on which environment you're calling into
  .build();

This code throwing the following error trace

java.lang.NoClassDefFoundError: com/google/gson/TypeAdapterFactory
	com.plaid.client.PlaidClient.newBuilder(PlaidClient.java:103)

**Comment by nicknadeau** [comment]
your project requires the Gson library
https://mvnrepository.com/artifact/com.google.code.gson/gson

**Comment by skylarmb** [comment]
hi there, closing this as stale / obsolete. You probably just need to add it to your pom.xml
