### ISSUE TITLE
How can i implement Plaid in Java web application, i am getting NoSuchMethodError: com.google.gson.GsonBuilder.registerTypeAdapterFactory

### ISSUE THREAD

**Issue by Villonava** [plaid/plaid-java#94]
Just i have added dependency in Maven pom.xml 

```
<dependency>
  <groupId>com.plaid</groupId>
  <artifactId>plaid-java</artifactId>
  <version>2.1.4</version>
</dependency>
```
After that i just added the following code

```
PlaidClient plaidClient = PlaidClient.newBuilder()
  .clientIdAndSecret("your_client_id", "your_secret")
  .publicKey("your_public_key") // optional. only needed to call endpoints that require a public key
  .sandboxBaseUrl() // or equivalent, depending on which environment you're calling into
  .build();
```

and i change my clientid, secret key and public key. This itself throws me  the following exception

> Sep 18, 2017 7:12:01 PM org.apache.catalina.core.StandardWrapperValve invoke SEVERE: Servlet.service() for servlet [mysample] in context with path [/mysample] threw exception [Handler processing failed; nested exception is java.lang.NoSuchMethodError: com.google.gson.GsonBuilder.registerTypeAdapterFactory(Lcom/google/gson/TypeAdapterFactory;)Lcom/google/gson/GsonBuilder;] with root cause java.lang.NoSuchMethodError: com.google.gson.GsonBuilder.registerTypeAdapterFactory(Lcom/google/gson/TypeAdapterFactory;)Lcom/google/gson/GsonBuilder; at com.plaid.client.PlaidClient$Builder.buildGson(PlaidClient.java:155) at com.plaid.client.PlaidClient$Builder.build(PlaidClient.java:145) at com.mysample.common.controller.MobileController.loginTz(MobileController.java:593) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:212) at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:126) at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:96) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:617) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:578) at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80) at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:900) at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:827) at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882) at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:789) at javax.servlet.http.HttpServlet.service(HttpServlet.java:641) at javax.servlet.http.HttpServlet.service(HttpServlet.java:722) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at com.mysample.security.filter.ValidationFilter.doFilter(ValidationFilter.java:359) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:311) at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:116) at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323) at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323) at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323) at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:54) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323) at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323) at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:201) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323) at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:182) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323) at com.mysample.security.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:167) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323) at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:105) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323) at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323) at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:173) at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346) at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:225) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98) at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1001) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:585) at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310) at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.lang.Thread.run(Unknown Source)

am i doing anything wrong? or could anyone help me to implement this in my web app

**Comment by mihahribar** [comment]
This worked for me:

```xml
<dependency>
    <groupId>com.plaid</groupId>
    <artifactId>plaid-java</artifactId>
    <version>2.1.2</version>
</dependency>
<dependency>
    <groupId>com.squareup.retrofit2</groupId>
    <artifactId>retrofit</artifactId>
    <version>2.3.0</version>
</dependency>
<dependency>
    <groupId>com.squareup.retrofit2</groupId>
    <artifactId>converter-gson</artifactId>
    <version>2.3.0</version>
</dependency>
<dependency>
    <groupId>com.squareup.okhttp3</groupId>
    <artifactId>okhttp</artifactId>
    <version>3.8.1</version>
</dependency>
```

**Comment by Villonava** [comment]
Hello @mihahribar  Thanks for your reply,

Earlier i used the following 

```
<dependency>
	      <groupId>com.squareup.retrofit2</groupId>
	      <artifactId>retrofit</artifactId>
	      <version>2.3.0</version>
	    </dependency>
	    <dependency>
	      <groupId>com.squareup.retrofit2</groupId>
	      <artifactId>converter-gson</artifactId>
	      <version>2.1.0</version>
	    </dependency>
	    <dependency>
	      <groupId>com.squareup.okhttp3</groupId>
	      <artifactId>okhttp</artifactId>
	      <version>3.9.0</version>
	    </dependency>
	    <dependency>
	      <groupId>com.squareup.okhttp3</groupId>
	      <artifactId>logging-interceptor</artifactId>
	      <version>3.6.0</version>
	    </dependency>
	    <dependency>
		  <groupId>com.plaid</groupId>
		  <artifactId>plaid-java</artifactId>
		  <version>2.1.4</version>
		</dependency>
```
Now i changed their versions as per yours. But still i am getting the same issue. First could you tell me the Step by step process of this implementation.

I just created API keys, added these in maven and added this Java code. Is it enough or do i need to link any other thing.

I am using Spring 3.9.0.

**Comment by mihahribar** [comment]
Sorry, not familiar with Spring. Might be they bundle something with the server that then conflicts with the version Plaid is using. Other than the comment above, I have no further info, sorry.

**Comment by Villonava** [comment]
Thank you for your useful info. Could you tell me in which platform you are using. And is it possible to download this repository and test it with my API keys. If yes please tell me in which platform or how you are using this.

**Comment by mihahribar** [comment]
We are using Wildfly, but it is a private repo - so no can do :)

**Comment by saurabh67** [comment]
I am also getting similar issue. Hey Villonava were you able to resolve the issue you were getting. If yes can you please share the info.

**Comment by skylarmb** [comment]
Hi there, closing this as it is not an issue with plaid-java, but feel free to add details here about how you solved the issue for future googlers

**Comment by Kakolu** [comment]
I had the same issue. I saw the same error even after I added 'com.google.gson' explicitly in my pom file.
This was because, there was another dependency in my project, that pulled an older version of gson, which in-turn did not have 'GsonBuilder.registerTypeAdapterFactory'.

What fixed it for me was updating the other dependency to a newer version.
